function mainMakeGraphs(dbid)

close all
% clear;
dbstop if error

if ~exist('dbid', 'var'),
    dbid = 3;
end

basepath = '../results/';
retpath = '../../separate/';

styles  = {'b-x','r-v','k-<','m-d','g-o', 'c-^','k--p','m-h','b-s','g-*','b->', 'c-*', 'c-', 'y->', 'y-'};

% names = {'DDVT', 'TLD(best)', 'TLD mask', ...
%         'TLD red', 'TLD green', 'TLD blue', ...
%         'TLD gray', 'TLD adjust', 'TLD opp2', 'TLD opp3',...
%         'TLD blue mask'};
% names = {'Proposed', 'MF', 'DT', 'DDVT', 'SCV', 'MI', 'SSD'};
% retfiles = {'../results/exp_test1.txt', ...
%             '../../separate/seq1_tld_test_best.txt', ...
%             '../../separate/seq1_tld_test_tldex.txt', ...
%             '../../separate/seq1_tld_test_red_s.txt', ...
%             '../../separate/seq1_tld_test_green_s.txt', ...
%             '../../separate/seq1_tld_test_blue_s.txt', ...
% %             '../../separate/seq1_tld_test_gray_s.txt', ...
% %             '../../separate/seq1_tld_test_adjust_s.txt', ...
% %             '../../separate/seq1_tld_test_opp2_s.txt', ...
% %             '../../separate/seq1_tld_test_opp3_s.txt', ...
%             '../../separate/seq1_tld_test_red_35.txt', ...
%             };
% '../../separate/seq1_tld_test_best.txt', ...
%-------------------------------------------------------------------------
% Full compare set
% names = {'Proposed', 'MF', 'DT', 'DDVT', 'FAST-DT', 'Reference', 'SSD'};
% retfiles = {'../../separate/seq1_tld_test_best.txt', ...
%             '../../separate/seq1_mf_test.txt', ...
%             '../../separate/seq1_dt_test.txt', ...
%             '../results/exp_test1.txt', ...
%             '../../separate/seq1_fast_dt_old.txt', ...
%             '../../separate/seq1_tld_test_fast_dt.txt', ...
%             };
%-------------------------------------------------------------------------
if dbid == 1,
names = {'DDVT', 'TLD', 'Proposed(0.65)','Proposed(0.60)','Proposed(0.55)','Proposed(0.50)',};
retfiles = {'../results/exp_test1.txt', ...
    '../../separate/seq1_tld_test_origin.txt', ...
    '../../separate/seq1_tld_test_fast_dt_conf0.65.txt', ...
    '../../separate/seq1_tld_test_fast_dt_conf0.60.txt', ...
    '../../separate/seq1_tld_test_fast_dt_conf0.55.txt', ...
    '../../separate/seq1_tld_test_fast_dt_conf0.50.txt', ...
    };
%-------------------------------------------------------------------------
retaccmats  = {'SCV_TEST1_tracker', 'MI_TEST1_tracker', 'SSD_TEST1_tracker'};
rethistmats = {'SCV_TEST1_tracker_b', 'MI_TEST1_tracker_b', 'SSD_TEST1_tracker_b'};
offset = 402;
anno = '../annotation_source/test1.txt';
end

%=============================
% names = {'Proposed', 'MF', 'DT', 'DDVT', 'FAST DT', 'SCV', 'MI', 'SSD'};
% retfiles = {'../../separate/seq2_tld_test_best.txt', ...
%             '../../separate/seq2_mf_test.txt', ...
%             '../../separate/seq2_dt_test.txt', ...
%             '../results/exp_test2.txt', ...
%             '../../separate/seq2_tld_test_fast_dt.txt', ...
%             };
% retaccmats  = {'SCV_TEST2_tracker', 'MI_TEST2_tracker', 'SSD_TEST2_tracker'};
% rethistmats = {'SCV_TEST2_tracker_b', 'MI_TEST2_tracker_b', 'SSD_TEST2_tracker_b'};
% offset = 229;
% anno = '../annotation_source/test2.txt';
%-------------------------------------------------------------------------
if dbid == 2,
names = {'DDVT', 'TLD', 'Proposed(0.65)','Proposed(0.60)','Proposed(0.55)','Proposed(0.50)',};
retfiles = {'../results/exp_test2.txt', ...
            '../../separate/seq2_tld_test_origin.txt', ...
            '../../separate/seq2_tld_test_fast_dt_conf0.65.txt', ...
            '../../separate/seq2_tld_test_fast_dt_conf0.60.txt', ...
            '../../separate/seq2_tld_test_fast_dt_conf0.55.txt', ...
            '../../separate/seq2_tld_test_fast_dt_conf0.50.txt', ...
            };
retaccmats  = {'SCV_TEST2_tracker', 'MI_TEST2_tracker', 'SSD_TEST2_tracker'};
rethistmats = {'SCV_TEST2_tracker_b', 'MI_TEST2_tracker_b', 'SSD_TEST2_tracker_b'};
offset = 229;
anno = '../annotation_source/test2.txt';
end
%-------------------------------------------------------------------------

% %=============================
% names = {'Proposed', 'MF', 'DT', 'TLD2', 'DDVT', 'SCV', 'MI', 'SSD', 'mask'};
% retfiles = {'../../separate/seq3_tld_test_best.txt', ...
%             '../../separate/seq3_mf_test.txt', ...
%             '../../separate/seq3_dt_test.txt', ...
%             '../../separate/seq3_new_test.txt', ...
%             '../results/exp_test3.txt', ...
%             '../../separate/seq3_new_mask.txt', ...
%             };
% retaccmats  = {'SCV_TEST3_tracker', 'MI_TEST3_tracker', 'SSD_TEST3_tracker'};
% rethistmats = {'SCV_TEST3_tracker_b', 'MI_TEST3_tracker_b', 'SSD_TEST3_tracker_b'};
% offset = 557;
% anno = '../annotation_source/test3.txt';
%-------------------------------------------------------------------------
if dbid == 3,
names = {'DDVT', 'TLD', 'Proposed(0.65)','Proposed(0.60)','Proposed(0.55)','Proposed(0.50)',};
retfiles = {'../results/exp_test3.txt', ...
            '../../separate/seq3_tld_test_origin.txt', ...
            '../../separate/seq3_tld_test_fast_dt_conf0.65.txt', ...
            '../../separate/seq3_tld_test_fast_dt_conf0.60.txt', ...
            '../../separate/seq3_tld_test_fast_dt_conf0.55.txt', ...
            '../../separate/seq3_tld_test_fast_dt_conf0.50.txt', ...
            };
retaccmats  = {'SCV_TEST3_tracker', 'MI_TEST3_tracker', 'SSD_TEST3_tracker'};
rethistmats = {'SCV_TEST3_tracker_b', 'MI_TEST3_tracker_b', 'SSD_TEST3_tracker_b'};
offset = 557;
anno = '../annotation_source/test3.txt';
end
%-------------------------------------------------------------------------

%=============================
if dbid == 4,
names = {'Proposed', 'MF', 'DT', 'DDVT', 'SCV', 'MI', 'SSD'};
retfiles = {'../../separate/seq4_tld_test_ct.txt', ...
            '../../separate/seq4_mf_test.txt', ...
            '../../separate/seq4_dt_test.txt', ...
            '../results/exp_laparoscopy1.txt', ...
            };
retaccmats  = {};
rethistmats = {};
offset = 0;
anno = '../annotation_source/lapatool1.txt';
end

%=============================
if dbid == 5,
names = {'Proposed', 'MF', 'DT', 'DDVT', 'SCV', 'MI', 'SSD'};
retfiles = {'../../separate/seq5_tld_test.txt', ...
            '../../separate/seq5_mf_test.txt', ...
            '../../separate/seq5_dt_test.txt', ...
            '../results/exp_laparoscopy2.txt', ...
            };
retaccmats  = {};
rethistmats = {};
offset = 0;
anno = '../annotation_source/lapatool2.txt';
end

% %=============================
% names = {'DDVT', 'TLD(best)', ...
%         'TLD+ct'};
% retfiles = {'../results/exp_test2.txt', ...
%             '../../separate/seq2_tld_test_best.txt', ...
%             '../../separate/seq2_tld_test_ct.txt', ...
%             };
% anno = '../annotation_source/test2.txt';
% %=============================
% names = {'DDVT', 'TLD(best)', ...
%         'TLD+ct'};
% retfiles = {'../results/exp_test3.txt', ...
%             '../../separate/seq3_tld_test_best.txt', ...
%             '../../separate/seq3_tld_test_ct.txt', ...
%             };
% anno = '../annotation_source/test3.txt';
% %=============================
% names = {'DDVT', 'TLD+op', 'TLD+red',...
%         };
% retfiles = {'../results/exp_laparoscopy1.txt', ...
%             '../../separate/seq4_tld_test_ct.txt', ...
%             '../../separate/seq4_tld_test_red.txt', ...
%             };
% anno = '../annotation_source/lapatool1.txt';
% %=============================
% names = {'DDVT', 'TLD+ct', ...
%         ''};
% retfiles = {'../results/exp_laparoscopy2.txt', ...
%             '../../separate/seq5_tld_test.txt', ...
%             };
% anno = '../annotation_source/lapatool2.txt';
% %=============================

AllAcc = {}; AllThr = {}; Hist = {};
F = 1:1000;%

for k = 1:length(retfiles)
    disp(names{k});
    [AllAcc{k} AllThr{k} Hist{k}] =  computeAccuracySigmaCurve(retfiles{k}, ...
                     anno,...
                     -1,...
                     -1);
end

% for j = 1:length(retaccmats)
%     load(retaccmats{j});
%     AllAcc{j+k} = Acc;
%     AllThr{j+k} = Thr;
%     load(rethistmats{j});
%     t = HIST(length(HIST)-offset:end);
%     %Hist{j+k}{2} = zeros(1, 1000);
%     Hist{j+k}{2} = computeContTracking(t);
% end
             
% ===========================================
figure;
for i = 1:length(AllThr)
    hold on;
    plot(AllThr{i}, AllAcc{i}, styles{i},'LineWidth',1.5); 
end
hold off;
xlim([15 40])
ylim([0 1])
xlabel(' Accuracy Threshold ','fontsize',20,'fontweight','b') 
ylabel(' Percent Detected   ','fontsize',20,'fontweight','b') 
set(gca,'YTick',[0 0.2 0.4 0.6 0.8 1])
set(gcf,'Position',[1 1 595 250]);

grid;
legend(names,'location','SouthEast');
set(gca,'fontsize',16) 

figure;
allHist = [];
ti = 1; 
for i = 1:length(AllThr)
    Hist{i}{2} = Hist{i}{2} /(Hist{i}{2}*F');
%     Hist{i}{ti} = Hist{i}{ti} /(Hist{i}{ti}*F');
    allHist = [allHist; Hist{i}{2}];
end
bar(allHist');
% title('  Exp 2a  ','fontsize',20,'fontweight','b');

xlim([0 10])
% ylim([0 .7])
xlabel(' Number of Consecutive Tracking Frames ','fontsize',20,'fontweight','b') 
ylabel(' Proportion of Frames   ','fontsize',20,'fontweight','b') 
set(gca,'YTick',[0.1 0.3 0.5 0.7])
set(gcf,'Position',[15 15 500 500 ]);

legend(names,'fontsize',14,'location','NorthEast');
set(gca,'fontsize',16) 
